import type { Tables } from "@/types/database"

export type ProductWithScore = Tables<"products_current"> & {
  trend_direction?: "up" | "stable" | "down"
}

export const MOCK_PRODUCTS: ProductWithScore[] = [
  {
    id: "mock-1",
    shopee_product_id: "sh-10001",
    title: "Fone Bluetooth TWS Pro Max Bass",
    price: 45.9,
    original_price: 89.9,
    rating: 4.8,
    sales_per_month: 3200,
    commission_percentage: 12,
    affiliate_link: "https://shopee.com.br/product/10001",
    rentability_score: 82,
    trend_score: 90,
    competition_level: "medium",
    competitors_count: 45,
    opportunity_score: 87,
    score_breakdown: {
      rentability: 82,
      trend: 90,
      competition: 75,
      price_appeal: 88,
      volume: 92,
    },
    recommended_ad_spend: 200,
    estimated_roi_percent: 185,
    estimated_monthly_profit: 540,
    last_scraped_at: new Date().toISOString(),
    last_analyzed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    trend_direction: "up",
  },
  {
    id: "mock-2",
    shopee_product_id: "sh-10002",
    title: "Camera de Seguranca WiFi 360 Full HD",
    price: 79.9,
    original_price: 149.9,
    rating: 4.6,
    sales_per_month: 1800,
    commission_percentage: 15,
    affiliate_link: "https://shopee.com.br/product/10002",
    rentability_score: 78,
    trend_score: 85,
    competition_level: "low",
    competitors_count: 22,
    opportunity_score: 78,
    score_breakdown: {
      rentability: 78,
      trend: 85,
      competition: 82,
      price_appeal: 72,
      volume: 68,
    },
    recommended_ad_spend: 350,
    estimated_roi_percent: 142,
    estimated_monthly_profit: 420,
    last_scraped_at: new Date().toISOString(),
    last_analyzed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    trend_direction: "up",
  },
  {
    id: "mock-3",
    shopee_product_id: "sh-10003",
    title: "Kit Maquiagem Completo 24 Pecas Profissional",
    price: 34.5,
    original_price: 69.9,
    rating: 4.5,
    sales_per_month: 2100,
    commission_percentage: 10,
    affiliate_link: "https://shopee.com.br/product/10003",
    rentability_score: 65,
    trend_score: 60,
    competition_level: "high",
    competitors_count: 89,
    opportunity_score: 65,
    score_breakdown: {
      rentability: 65,
      trend: 60,
      competition: 45,
      price_appeal: 80,
      volume: 75,
    },
    recommended_ad_spend: 150,
    estimated_roi_percent: 95,
    estimated_monthly_profit: 180,
    last_scraped_at: new Date().toISOString(),
    last_analyzed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    trend_direction: "stable",
  },
  {
    id: "mock-4",
    shopee_product_id: "sh-10004",
    title: "Organizador de Maquiagem Acrilico Giratorio",
    price: 52.0,
    original_price: 89.0,
    rating: 4.3,
    sales_per_month: 950,
    commission_percentage: 8,
    affiliate_link: "https://shopee.com.br/product/10004",
    rentability_score: 55,
    trend_score: 50,
    competition_level: "medium",
    competitors_count: 34,
    opportunity_score: 55,
    score_breakdown: {
      rentability: 55,
      trend: 50,
      competition: 60,
      price_appeal: 58,
      volume: 42,
    },
    recommended_ad_spend: 100,
    estimated_roi_percent: 72,
    estimated_monthly_profit: 95,
    last_scraped_at: new Date().toISOString(),
    last_analyzed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    trend_direction: "stable",
  },
  {
    id: "mock-5",
    shopee_product_id: "sh-10005",
    title: "Capa iPhone 15 Pro Max Silicone Premium",
    price: 19.9,
    original_price: null,
    rating: 4.1,
    sales_per_month: 5400,
    commission_percentage: 6,
    affiliate_link: "https://shopee.com.br/product/10005",
    rentability_score: 40,
    trend_score: 30,
    competition_level: "high",
    competitors_count: 150,
    opportunity_score: 42,
    score_breakdown: {
      rentability: 40,
      trend: 30,
      competition: 25,
      price_appeal: 65,
      volume: 95,
    },
    recommended_ad_spend: 50,
    estimated_roi_percent: 35,
    estimated_monthly_profit: 45,
    last_scraped_at: new Date().toISOString(),
    last_analyzed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    trend_direction: "down",
  },
  {
    id: "mock-6",
    shopee_product_id: "sh-10006",
    title: "Luminaria LED Mesa Escritorio Touch Dimmer",
    price: 62.0,
    original_price: 120.0,
    rating: 4.7,
    sales_per_month: 1400,
    commission_percentage: 14,
    affiliate_link: "https://shopee.com.br/product/10006",
    rentability_score: 76,
    trend_score: 82,
    competition_level: "low",
    competitors_count: 18,
    opportunity_score: 81,
    score_breakdown: {
      rentability: 76,
      trend: 82,
      competition: 88,
      price_appeal: 74,
      volume: 62,
    },
    recommended_ad_spend: 250,
    estimated_roi_percent: 158,
    estimated_monthly_profit: 380,
    last_scraped_at: new Date().toISOString(),
    last_analyzed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    trend_direction: "up",
  },
  {
    id: "mock-7",
    shopee_product_id: "sh-10007",
    title: "Mini Projetor Portatil LED 4K WiFi HDMI",
    price: 189.9,
    original_price: 399.9,
    rating: 4.4,
    sales_per_month: 780,
    commission_percentage: 18,
    affiliate_link: "https://shopee.com.br/product/10007",
    rentability_score: 88,
    trend_score: 78,
    competition_level: "low",
    competitors_count: 12,
    opportunity_score: 84,
    score_breakdown: {
      rentability: 88,
      trend: 78,
      competition: 90,
      price_appeal: 68,
      volume: 45,
    },
    recommended_ad_spend: 500,
    estimated_roi_percent: 210,
    estimated_monthly_profit: 820,
    last_scraped_at: new Date().toISOString(),
    last_analyzed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    trend_direction: "up",
  },
  {
    id: "mock-8",
    shopee_product_id: "sh-10008",
    title: "Relogio Smartwatch Bluetooth Monitor Cardiaco",
    price: 75.0,
    original_price: 159.0,
    rating: 4.2,
    sales_per_month: 2800,
    commission_percentage: 11,
    affiliate_link: "https://shopee.com.br/product/10008",
    rentability_score: 70,
    trend_score: 65,
    competition_level: "high",
    competitors_count: 95,
    opportunity_score: 62,
    score_breakdown: {
      rentability: 70,
      trend: 65,
      competition: 38,
      price_appeal: 72,
      volume: 85,
    },
    recommended_ad_spend: 200,
    estimated_roi_percent: 88,
    estimated_monthly_profit: 210,
    last_scraped_at: new Date().toISOString(),
    last_analyzed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    trend_direction: "stable",
  },
]

export const MOCK_HISTORY = [
  { date: "2026-01-15", price: 49.9, sales: 2800 },
  { date: "2026-01-22", price: 47.5, sales: 2950 },
  { date: "2026-01-29", price: 45.9, sales: 3100 },
  { date: "2026-02-05", price: 45.9, sales: 3050 },
  { date: "2026-02-12", price: 44.0, sales: 3200 },
  { date: "2026-02-19", price: 45.9, sales: 3150 },
  { date: "2026-02-26", price: 45.9, sales: 3200 },
  { date: "2026-03-05", price: 43.5, sales: 3400 },
]

export const SHOPEE_CATEGORIES = [
  { id: "electronics", name: "Eletronicos" },
  { id: "fashion", name: "Moda" },
  { id: "beauty", name: "Beleza" },
  { id: "home", name: "Casa e Decoracao" },
  { id: "sports", name: "Esportes" },
  { id: "toys", name: "Brinquedos" },
  { id: "automotive", name: "Automotivo" },
  { id: "pets", name: "Pet Shop" },
  { id: "health", name: "Saude" },
  { id: "baby", name: "Bebes" },
]
